# Generated by Django 5.1.7 on 2025-06-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
