# Generated by Django 5.1.7 on 2025-06-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0004_customuser_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profilePicture',
        ),
    ]
