# Generated by Django 5.1.7 on 2025-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0005_remove_customuser_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
