# Generated by Django 5.1.7 on 2025-06-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0006_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitudine',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitudine',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
