# Generated by Django 5.1.7 on 2025-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0007_event_latitudine_event_longitudine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitudine',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitudine',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
    ]
