# Generated by Django 5.1.7 on 2025-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0008_alter_event_latitudine_alter_event_longitudine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitudine',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitudine',
            field=models.FloatField(null=True),
        ),
    ]
