# Generated by Django 5.1.7 on 2025-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0009_alter_event_latitudine_alter_event_longitudine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Earlybird', 'Earlybird'), ('General entry', 'General entry'), ('VIP', 'VIP')], max_length=200, null=True),
        ),
    ]
