# Generated by Django 5.1.7 on 2025-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanzareBilete', '0010_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='colorTheme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
